### PR TITLE
Spanish translation

### PR DESCRIPTION
**Pull request by llabori-venehsoftw**
This PR contains the Spanish translations of each of the existing .mdx files in the REPO for the MADARA project documentation. The translation for the README.md file is also included.

### CODE REVIEW

**Comment by dpinones** [comment]
Hey @llabori-venehsoftw what is missing from this PR to get it merged? Did you follow this documentation at https://nextra.site/docs/guide/i18n?

**Comment by llabori-venehsoftw** [comment]
> Hey @llabori-venehsoftw what is missing from this PR to get it merged? Did you follow this documentation at

Hey dpinones unfortunately I was without a machine for a few days ..... and now I'm almost with a borrowed machine to which I can not be installing practically nothing. So I'm looking for the mechanism to be able to finish the PR. For the documentation I have no problem, I already know what is wrong and what does not make it merge.

**Comment by dpinones** [comment]
> > Hey @llabori-venehsoftw what is missing from this PR to get it merged? Did you follow this documentation at
> 
> Hey dpinones unfortunately I was without a machine for a few days ..... and now I'm almost with a borrowed machine to which I can not be installing practically nothing. So I'm looking for the mechanism to be able to finish the PR. For the documentation I have no problem, I already know what is wrong and what does not make it merge.

Great @llabori-venehsoftw! If you need help, let me know  🙂

**Comment by joseSalazar4** [comment]
Is this still going on? I would like to give a couple of suggestions that might make things clearer if there's a chance to work upon this.

**Comment by llabori-venehsoftw** [comment]
> Is this still going on? I would like to give a couple of suggestions that might make things clearer if there's a chance to work upon this.

Very good morning/afternoon/evening dear Jose;

I had lost track of you in the many things I am currently working on, but I would like to thank you for your help in obtaining the final result.

**Pull request closed without merging**
